apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdCluster"
metadata:
  name: "example-etcd-cluster"
  ## Adding this annotation make this cluster managed by clusterwide operators
  ## namespaced operators ignore it
  # annotations:
  #   etcd.database.coreos.com/scope: clusterwide
spec:
  size: 3
  version: "3.5.2"
  repository: "hub.docker.hpecorp.net/nvgrid/etcd"
  pod:
    ClusterDomain: ".cluster.local"
    persistentVolumeClaimSpec:
      storageClassName: "example-storage-class"
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
